export const ActionType = {
    SIGN_UP: "SIGN_UP",
    SIGN_IN: "SIGN_IN",
    SIGN_OUT: "SIGN_OUT",
    USER_LIST_SUCCESS: "USER_LIST_SUCCESS",
    CATEGORY_LIST_SUCCESS: "CATEGORY_LIST_SUCCESS",
    ADD_PRODUCT: "ADD_PRODUCT",
    PRODUCT_LIST_SUCCESS: "PRODUCT_LIST_SUCCESS",
    PRODUCT_DETAILS_SUCCESS: "PRODUCT_DETAILS_SUCCESS",
    CART_LIST : "CART_LIST",
    ORDER_LIST : "ORDER_LIST",
}